services:
  api:
    build: .
    ports:
      - "8200:8000"

    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/


  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      

volumes:
  mongodb_data:
